### PR TITLE
Cargo fmt

### PR DESCRIPTION
**Pull request by DutchGhost**
Running rustfmt in the playground adds some spaces.

### CODE REVIEW

**Comment by Lokathor** [comment]
that's because the playground uses the evil 4space indent, but i use the good 2space indent

**Comment by Nemo157** [comment]
Please consider adding a `rustfmt.toml` and `.editorconfig` stating that, so contributors don't accidentally reintroduce the evil 4spaces.

**Comment by Lokathor** [comment]
opened https://github.com/Lokathor/uwu/issues/2 as tracking that problem

**Comment by Lokathor** [comment]
Resolved!

**Pull request closed without merging**
